[package]
name = "shm-artifact"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shm-core = { workspace = true }
shm-arrow = { workspace = true }
shm-ring = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = "58"
thiserror = { workspace = true }

[dev-dependencies]
arrow-buffer = { workspace = true }
tempfile = { workspace = true }
