[package]
name = "shm-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shm-core = { workspace = true }
shm-arrow = { workspace = true }
shm-ring = { workspace = true }
shm-task = { workspace = true }
shm-artifact = { workspace = true }
shm-stream = { workspace = true }
shm-store = { workspace = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "shm-skeleton"
path = "src/bin/shm-skeleton.rs"

[[bin]]
name = "shm-cacheloop"
path = "src/bin/shm-cacheloop.rs"

[[bin]]
name = "shm-store-skeleton"
path = "src/bin/shm-store-skeleton.rs"

[[bin]]
name = "shm-g1-skeleton"
path = "src/bin/shm-g1-skeleton.rs"
