[package]
name = "shm-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shm-core.workspace = true
shm-arrow.workspace = true
shm-artifact.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
bytemuck = { workspace = true }
thiserror.workspace = true
